# UI Colors (extended)
accent = "#8dacf7"
cursor = "#F2E4D0"

# Primary colors
foreground = "#F2E4D0"
background = "#0C0402"

# Selection colors
selection_foreground = "#0C0402"
selection_background = "#F2E4D0"

# Normal colors (ANSI 0-7)
color0 = "#0C0402"
color1 = "#D76640"
color2 = "#E6C889"
color3 = "#EED396"
color4 = "#8dacf7"
color5 = "#d593d5"
color6 = "#2dc5c5"
color7 = "#F2E4D0"

# Bright colors (ANSI 8-15)
color8 = "#6e6864"
color9 = "#ff8755"
color10 = "#f7d885"
color11 = "#fde191"
color12 = "#abcaff"
color13 = "#fcaeff"
color14 = "#43e9e9"
color15 = "#f1e3ca"
