# Background and foreground colors
background = #0C0402
foreground = #F2E4D0

# Standard colors
palette = 0=#0C0402
palette = 1=#D76640
palette = 2=#E6C889
palette = 3=#EED396
palette = 4=#8dacf7
palette = 5=#d593d5
palette = 6=#2dc5c5
palette = 7=#F2E4D0

# Bright colors
palette = 8=#6e6864
palette = 9=#ff8755
palette = 10=#f7d885
palette = 11=#fde191
palette = 12=#abcaff
palette = 13=#fcaeff
palette = 14=#43e9e9
palette = 15=#f1e3ca
