$color = rgba(12, 4, 2, 1)
$inner_color = rgba(12, 4, 2, 0.66)
$outer_color = rgba(213, 147, 213, 1)
$font_color = rgba(242, 228, 208, 1)
$placeholder_color = rgba(242, 228, 208, 0.7)
$check_color = rgba(45, 197, 197, 1)
