background            #0C0402
foreground            #F2E4D0

# black
color0  #0C0402
color8  #6e6864

# red
color1  #D76640
color9  #ff8755

# green
color2  #E6C889
color10 #f7d885

# yellow
color3  #EED396
color11 #fde191

# blue
color4  #8dacf7
color12 #abcaff

# magenta
color5  #d593d5
color13 #fcaeff

#cyan
color6  #2dc5c5
color14 #43e9e9

#white
color7  #F2E4D0
color15 #f1e3ca


